"""create_users_table

Revision ID: 40a5624b9f38
Revises: 44edd61a5c02
Create Date: 2026-02-04 16:17:29.846372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40a5624b9f38'
down_revision: Union[str, Sequence[str], None] = '44edd61a5c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
