"""remove_player_id_fk_from_game_events

Revision ID: 44e1a896e6b7
Revises: c4a52c13342c
Create Date: 2026-03-05 20:23:53.843988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '44e1a896e6b7'
down_revision: Union[str, Sequence[str], None] = 'c4a52c13342c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_game_participants_user_id'), table_name='game_participants')
    op.drop_table('game_participants')
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.drop_constraint('game_events_ibfk_2', 'game_events', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('game_events_ibfk_2'), 'game_events', 'users', ['player_id'], ['id'])
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.create_table('game_participants',
    sa.Column('game_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('game_participants_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('game_participants_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_game_participants_user_id'), 'game_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###
