"""Add user_id to games table

Revision ID: ad007d3ff8c0
Revises: 44e1a896e6b7
Create Date: 2026-03-05 20:50:19.684560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad007d3ff8c0'
down_revision: Union[str, Sequence[str], None] = '44e1a896e6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=True, comment='所属用户ID'))
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

    # --- Data Backfill ---
    from sqlalchemy.orm import Session
    from sqlalchemy import text
    import json

    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        # Get all games
        games = session.execute(text("SELECT id, player_ids FROM games")).fetchall()
        
        # Get all real user IDs
        real_user_ids = set(row[0] for row in session.execute(text("SELECT id FROM users")).fetchall())

        for game in games:
            game_id = game[0]
            player_ids_raw = game[1]
            
            # Handle JSON parsing
            if isinstance(player_ids_raw, str):
                try:
                    player_ids = json.loads(player_ids_raw)
                except:
                    player_ids = []
            elif isinstance(player_ids_raw, list):
                player_ids = player_ids_raw
            else:
                player_ids = []

            # Find the real user
            found_user_id = None
            for pid in player_ids:
                if pid in real_user_ids:
                    found_user_id = pid
                    break
            
            if found_user_id:
                session.execute(
                    text("UPDATE games SET user_id = :uid WHERE id = :gid"),
                    {"uid": found_user_id, "gid": game_id}
                )
        
        session.commit()
    except Exception as e:
        print(f"Data migration failed: {e}")
        session.rollback()
        raise e
    finally:
        session.close()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_column('games', 'user_id')
    # ### end Alembic commands ###
