"""check_schema_consistency

Revision ID: bd13848a4a56
Revises: ad007d3ff8c0
Create Date: 2026-03-05 23:48:56.341528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd13848a4a56'
down_revision: Union[str, Sequence[str], None] = 'ad007d3ff8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'games_good')
    op.drop_column('users', 'games_evil')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('games_evil', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('games_good', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
