"""add_game_participants_and_optimize_indexes

Revision ID: c4a52c13342c
Revises: d86ccacfc408
Create Date: 2026-03-03 18:57:44.019405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a52c13342c'
down_revision: Union[str, Sequence[str], None] = 'd86ccacfc408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_participants',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_index(op.f('ix_game_participants_user_id'), 'game_participants', ['user_id'], unique=False)
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.drop_index(op.f('ix_game_participants_user_id'), table_name='game_participants')
    op.drop_table('game_participants')
    # ### end Alembic commands ###
