"""add_user_stats

Revision ID: d86ccacfc408
Revises: 7a2b3c4d5e6f
Create Date: 2026-02-27 00:07:32.195494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86ccacfc408'
down_revision: Union[str, Sequence[str], None] = '7a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_games', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wins_good', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wins_evil', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_wins')
    op.drop_column('users', 'wins_evil')
    op.drop_column('users', 'wins_good')
    op.drop_column('users', 'total_games')
    # ### end Alembic commands ###
