"""create game and game_events tables

Revision ID: e14ad4306443
Revises: 40a5624b9f38
Create Date: 2026-02-21 17:36:59.521181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14ad4306443'
down_revision: Union[str, Sequence[str], None] = '40a5624b9f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False, comment='对局ID (UUID)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='当前状态'),
    sa.Column('winner', sa.String(length=16), nullable=True, comment='获胜阵营'),
    sa.Column('player_ids', sa.JSON(), nullable=False, comment='参与玩家ID列表'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False, comment='事件序号，从1开始'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='事件类型 (ActionType)'),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='触发玩家ID'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='事件详情数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_events_id'), 'game_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_events_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
